services:
  geo-transit-backend:
    container_name: nestjs-api-geotransit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:3000" 

    env_file:
      - .env
